### ISSUE TITLE
ClojureDart Support - Tracker

### ISSUE THREAD

**Issue by SignSpice** [hyperfiddle/electric#18]
Issues that would need to be resolved to support ClojureDart:  

- [ ] Waiting for ClojureDart
  - [ ] `defmulti`/`defmethod` https://github.com/Tensegritics/ClojureDart/issues/3
- [ ] Convert every .clj file to .cljc or add .cljd variant (including dependancies) 

Probably others also, but this is what I am aware of so far.
